[package]
name = "libnscache"
version = "0.1.0"
edition = "2021"

[lib]
name         = "nscache"
crate-type   = ["cdylib"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
ctor = "0.2.6"
lazy_static = "1.4.0"
libc = "0.2.152"
